### ISSUE TITLE
Diagrama de Gantt: Back-end

### ISSUE THREAD

**Issue by alexitoguiz** [UNIZAR-30226-2020-03/Spring-back#1]
Realización del diagrama de Gantt para el back-end

**Comment by Piedrafita** [comment]
[Diagrama_gantt_backend.xlsx](https://github.com/UNIZAR-30226-2020-03/Spring-back/files/4334322/Diagrama_gantt_backend.xlsx)

Los últimos mensajes no se consiguen ver correctamente (las últimas burbujas del diagrama)

**Comment by alexitoguiz** [comment]
Realizado y subido a la memoria
