### ISSUE TITLE
Creación de playlist

### ISSUE THREAD

**Issue by alexitoguiz** [UNIZAR-30226-2020-03/Spring-back#14]

**Comment by Piedrafita** [comment]
### Playlist v1

Creación Playlist (modelo):
0320d785cf9faaa1b8e62f0167045413aef297d7

Creación Playlist (DAO, Service y API con Request y Response):
02407f14fff9f3c1336c3b4833433cec6b60a63b

**Comment by Piedrafita** [comment]
### Playlist v2 - CREADOR

Solucionado mapeo Playlist <-> Creador finalmente:
3c041572c7818f8f8fa4432ebad16a56c4008cf6

Probadas todas las posibilidades

**Comment by Piedrafita** [comment]
### Playlist FINAL - CANCIONES

d55a3c1dce73eee6661a078eaca920d103ca6a2d

+ Solución error en mapeado:
7cb668498c54f5f5f955d61a20c65e24748f4a57

**Comment by Piedrafita** [comment]
### Fix en CancionRequest y CancionResponse

Corregidos/añadidos datos de Cancion:
15536471142b545adc62e4819d4c92a3b6f4a463

Asociado a #13 

Con esto, quedan probadas todas las posibilidades, visualizándose correctamente
