### ISSUE TITLE
Creación de funcionalidades de red social

### ISSUE THREAD

**Issue by alexitoguiz** [UNIZAR-30226-2020-03/Spring-back#16]

**Comment by Piedrafita** [comment]
### Amigos v1
Creación en el modelo

e3ca5e926291cb4b9057db50510a7912eb3689f7
b5ce43f1fce398e78f579b79caba7e3830dfbfd0

**Comment by Piedrafita** [comment]
### Amigos v2
Operación addAmigo + Operación follow API

526a3b97267210d16b304851030ac8d184d43b4a

**Comment by Piedrafita** [comment]
### Amigos v3
Operaciones unfollow + following. Actualización modelo

8b2958a6d31bbcb50b05e53c3c7aa179e51cfb4e

**Comment by Piedrafita** [comment]
### Amigos v4

Fix errores:
961decd7af90f4e470fb12dd082201c178f4138d

Búsqueda por nombre de usuario:
0e7998815028dac07ac3667508dec03cd93adebb

Códigos de error en las funciones:
ee9c5e9b56167b1e6628bcd54b67596514e6c44e

Lista siguiendo:
2898f31370a315bceabd1fb9dd3f469f5fc94ddb

**Comment by Piedrafita** [comment]
### Amigos FINAL (Usuario)

Solución de errores para finalizar red social:
c3149168673d3b078ca7130ad8747a08dd203b88
ae67947c14e069d5271f7c40ec7e89ad6bbe8ecd
5a56f45b87a7be24633e4a45a5c51766bcf64906

RED SOCIAL FUNCIONA Y PROBADA POR FRONT -> debido a mala comprensión de los RF, implementado en Usuario. Habrá que migrar a Cliente para que tanto usuarios como artistas puedan seguirse.

**Comment by Piedrafita** [comment]
### AMIGOS FINAL

Migración a Cliente:
3c0f82e87db686288248750246138814245f0dd3

Solución recursividad infinita al obtener clientes y sus amigos:
874972dffb67f34cd527737c9bf443200207a774
