### ISSUE TITLE
Lista Favoritos del Cliente

### ISSUE THREAD

**Issue by Piedrafita** [UNIZAR-30226-2020-03/Spring-back#18]
Lista de canciones favoritas de cada cliente, asignada a @alexitoguiz

**Comment by alexitoguiz** [comment]
Realizados para canción y Playlist

**Comment by alexitoguiz** [comment]
dff45f73c4ec8994f48aef2b29baf20bb388c940

**Comment by alexitoguiz** [comment]
Realizados los cambios y funciona todo okey, Podcast + Álbum
07f313c45f30abb59855cfa3a06fd2da9c54de05
