### ISSUE TITLE
Procesos técnicos: back-end

### ISSUE THREAD

**Issue by alexitoguiz** [UNIZAR-30226-2020-03/Spring-back#2]
Describir los métodos, herramientas y técnicas necesarios tanto para construir el software (p.ej. herramientas de desarrollo) como para desplegarlo y probarlo (todos los necesarios para dar soporte a los planes descritos en la sección 3.2 (Planes)).

**Comment by vitolo99** [comment]
Subido borrador tecnologías streaming

**Comment by vitolo99** [comment]
@alexitoguiz

**Comment by alexitoguiz** [comment]
Realizado hoy y añadido a la memoria
