### ISSUE TITLE
Creación de la entidad Cliente

### ISSUE THREAD

**Issue by alexitoguiz** [UNIZAR-30226-2020-03/Spring-back#3]

**Comment by Piedrafita** [comment]
### Cliente v1

defe7a494e1bbd3d3d399eacb32c1c1551f99155

**Comment by Piedrafita** [comment]
### Mapeo Request y Response -> APIs

8228bdd4ec059344d18bc8c5b9e657c3234dbf22

**Comment by Piedrafita** [comment]
### FINAL Cliente

34cb97ef6655b2f554e6fb947813ff3636b44739

Hecho junto a @alexitoguiz y con la ayuda de @SanTa45zgz
