### ISSUE TITLE
Creación de la entidad Artista y Usuario

### ISSUE THREAD

**Issue by alexitoguiz** [UNIZAR-30226-2020-03/Spring-back#4]

**Comment by Piedrafita** [comment]
### Usuario v1

0214985e08d949e0fed805842652bab96fd587ff

**Comment by Piedrafita** [comment]
### Mapeado API Request y Response

2e1ba88ce16c50e9abb7a70d062e30eee47c3278

**Comment by Piedrafita** [comment]
### Artista

a8978ac38194e7636947e7c8fc46682a2db4864a

**Comment by Piedrafita** [comment]
### FINAL Usuario Y Artista

Usuario:
ffdf4ef5fbfa1952ff1cadfc5726579fde6d14b5

Artista:
17d493bee8f3f74b2c6a09b0cbafa3dd31ce3e20
