### ISSUE TITLE
Acuerdo con front-end sobre estándares de conexión y tipo de datos

### ISSUE THREAD

**Issue by alexitoguiz** [UNIZAR-30226-2020-03/Spring-back#7]

**Comment by Piedrafita** [comment]
### Cliente, Usuario, Artista
Clases tienen su propia URL (/cliente, /usuario, /artista)

Dentro de cada clase, mismas operaciones: 
/get/{correo}
/get/{contrasenya}/{correo}
/allClientes
/save
/update/{correo}
/delete/{correo}

Junto con: @alexitoguiz y notificado a web y móvil

**Comment by Piedrafita** [comment]
### Operaciones red social
/cliente...
    /follow/{miCorreo}/{suCorreo}
    /following/{miCorreo}/{suCorreo}
    /unfollow/{miCorreo}/{suCorreo}
    /followingList/{miCorreo}

Notificado al front via Whatsapp previamente

**Comment by Piedrafita** [comment]
### Operaciones Playlists
Para que los clientes creen y manipulen playlists:
/cliente...
/createPlaylist/{miCorreo}/{playlistId}
/myPlaylists/{miCorreo}
/isMyPlaylist/{miCorreo}/{playlistId}

Operaciones CRUD de Playlist
/playlist...
/get/{id}
/getByName/{name}
/allPlaylists
/save
/update/{id}
/delete/{id}

Manipulación canciones de una playlist:
/addSong/{idPlaylist}/{idSong}
/isInPlaylist/{idPlaylist}/{idSong}
/takeOut/{idPlaylist}/{idSong}
/songList/{id}

Notificado al front via Whatsapp previamente

**Comment by Piedrafita** [comment]
### Operaciones Cancion

Explicar @vitolo99

**Comment by Piedrafita** [comment]
### Operacines Favoritos

Explicar @alexitoguiz

**Comment by Piedrafita** [comment]
### Operaciones Álbumes
Para que los artistas creen y manipulen álbumes:
/artista...
/createAlbum/{miCorreo}/{albumId}
/myAlbums/{miCorreo}
/isMyAlbum/{miCorreo}/{albumId}

Operaciones CRUD de Album
/album...
/get/{id}
/getByName/{name}
/allAlbums
/save
/update/{id}
/delete/{id}

Manipulación canciones de un álbum:
/addSong/{idAlbum}/{idSong}
/isInAlbum/{idAlbum}/{idSong}
/takeOut/{idAlbum}/{idSong}
/songList/{id}

Notificado al front via Whatsapp previamente

**Comment by vitolo99** [comment]
terminados
